apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: chainlink-polygon-metrics-servicemonitor-1
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      statefulset.kubernetes.io/pod-name: chainlink-polygon-1
  namespaceSelector:
    matchNames:
      - chainlink-polygon
  podMetricsEndpoints:
  - targetPort: 6688
    path: /metrics
    interval: 15s
  podTargetLabels:
    - chainlink-polygon